### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by ganghe74** [ganghe74/dotfiles#11]
- [ ] solve.py -r 에서 testcase 폴더 요구하는 것 없애기
- [ ] cronie, neovim, stow 등 리눅스 처음깔았을때 필요한 것들 문서화하기
- [ ] windows 폴더 내용 windows.md 등으로 바꿔서 docs폴더 만들어서 리눅스랑 같이 정리하기
